# Generated by Django 6.0.7 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=200, verbose_name='تگ محصول')),
            ],
            options={
                'verbose_name': 'تگ محصول',
                'verbose_name_plural': 'تگ های محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('title_url', models.CharField(db_index=True, max_length=200)),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),  # pyright: ignore[reportArgumentType]
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),  # pyright: ignore[reportArgumentType]
                ('short_Description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات مفصل')),
                ('slug', models.SlugField(default='', max_length=200, unique=True, verbose_name='url محصول')),
                ('captions', models.ManyToManyField(related_name='captions', to='eshop.captionp', verbose_name='کپشن ها')),
                ('category', models.ManyToManyField(related_name='products', to='eshop.productcategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
