# Generated by Django 6.0.7 on 2026-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaptionP',
            new_name='HashtagP',
        ),
        migrations.AlterModelOptions(
            name='hashtagp',
            options={'verbose_name': 'هشتگ محصول', 'verbose_name_plural': 'هشتگ های محصول'},
        ),
        migrations.RenameField(
            model_name='hashtagp',
            old_name='caption',
            new_name='hashtag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='short_Description',
            new_name='short_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='captions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='eshop.productcategory', verbose_name='دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(related_name='hashtags', to='eshop.hashtagp', verbose_name='هشتگ ها'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/نشده'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/نشده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=20, verbose_name='قیمت'),
        ),
    ]
